name: Deploy to AWS ECS

on:
  push:
    branches: ["ecs-deployment"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Auth into Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: cd app && docker build -t taranjeetsingh/boloons-api-ecs .

      - name: Push to Docker Hub
        run: docker push taranjeetsingh/boloons-api-ecs
      - name: Install cdk
        run: cd ..

      - name: Create cloudformation stack
        run: cd cdk && npm install && npm install -g aws-cdk && cdk deploy --require-approval never
